
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Button btnAbout;
	
	private global::Gtk.Entry txtStatus;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Button btnShutdown;
	
	private global::Gtk.Button btnRestart;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Restart2UEFIMONO.Resources.24x24R2uefi.png");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.AllowShrink = true;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnAbout = new global::Gtk.Button ();
		this.btnAbout.CanFocus = true;
		this.btnAbout.Name = "btnAbout";
		this.btnAbout.UseUnderline = true;
		this.btnAbout.Label = global::Mono.Unix.Catalog.GetString ("  ?  ");
		this.hbox1.Add (this.btnAbout);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnAbout]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.txtStatus = new global::Gtk.Entry ();
		this.txtStatus.CanFocus = true;
		this.txtStatus.Name = "txtStatus";
		this.txtStatus.IsEditable = false;
		this.txtStatus.InvisibleChar = '●';
		this.hbox1.Add (this.txtStatus);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtStatus]));
		w2.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnShutdown = new global::Gtk.Button ();
		this.btnShutdown.WidthRequest = 200;
		this.btnShutdown.HeightRequest = 100;
		this.btnShutdown.CanFocus = true;
		this.btnShutdown.Name = "btnShutdown";
		this.btnShutdown.UseUnderline = true;
		this.btnShutdown.Label = global::Mono.Unix.Catalog.GetString ("  Set firmware flag \n    and Shutdown");
		global::Gtk.Image w4 = new global::Gtk.Image ();
		w4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Restart2UEFIMONO.Resources.smallshutdown.png");
		this.btnShutdown.Image = w4;
		this.hbox2.Add (this.btnShutdown);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnShutdown]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.btnRestart = new global::Gtk.Button ();
		this.btnRestart.WidthRequest = 200;
		this.btnRestart.HeightRequest = 114;
		this.btnRestart.CanFocus = true;
		this.btnRestart.Name = "btnRestart";
		this.btnRestart.UseUnderline = true;
		this.btnRestart.Label = global::Mono.Unix.Catalog.GetString ("  Set firmware flag \n     and Restart");
		global::Gtk.Image w6 = new global::Gtk.Image ();
		w6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Restart2UEFIMONO.Resources.smallrestart.png");
		this.btnRestart.Image = w6;
		this.hbox2.Add (this.btnRestart);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.btnRestart]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 406;
		this.DefaultHeight = 157;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnAbout.Clicked += new global::System.EventHandler (this.OnBtnAboutClicked);
		this.btnShutdown.Clicked += new global::System.EventHandler (this.OnBtnShutdownClicked);
		this.btnRestart.Clicked += new global::System.EventHandler (this.OnBtnRestartClicked);
	}
}
